Repository containerish/OpenRegistry, pull requests merged in 2022-02, with the labels that each got.

#98 Feat: added api to list user catalog with pagination
  registry/v2/registry.go
  store/postgres/container_image.go
  store/postgres/postgres.go
  store/postgres/queries/registry.go
  types/types.go
Labels: P2

#100 Refactor: Using Skynet SDK's Metadata API
  go.mod
  go.sum
  registry/v2/blobs.go
  registry/v2/registry.go
  skynet/skynet.go
Labels: P3

#101 Chore: Adds cancel-in-progress on consecutive push
  .github/workflows/golangci-lint.yml
  .github/workflows/oci-dist-spec-content-discovery.yml
  .github/workflows/oci-dist-spec-content-management.yml
  .github/workflows/oci-dist-spec-pull.yml
  .github/workflows/oci-dist-spec-push.yml
Labels: Chore, CI

#105 Chore: OCI Certification Badge
  README.md
Labels: Chore
