Repository containerish/OpenRegistry, pull requests merged in 2022-03, with the labels that each got.

#112 Feat: basic implementation for search for auto-completion api
  db/migrations/000004_create_config_table.up.sql
  registry/v2/registry.go
  registry/v2/types.go
  router/route_names.go
  router/router.go
  store/postgres/container_image.go
  store/postgres/postgres.go
  store/postgres/queries/registry.go
Labels: enhancement, P1

#113 Fix: Skynet Portal URL from config file
  config.yaml.example
  config/config.go
Labels: bug

#114 Fix: removed io.ReadAll from entire project
  auth/signup.go
  registry/v2/blobs.go
  registry/v2/registry.go
Labels: enhancement

#123 Feat: added console writer for local logging
  auth/basic_auth.go
  auth/jwt_middleware.go
  auth/signin.go
  auth/signup.go
  auth/token.go
  go.mod
  go.sum
  main.go
  registry/v2/blobs.go
  registry/v2/helpers.go
  registry/v2/registry.go
  telemetry/consoleWriter.go
  telemetry/log.go
Labels: enhancement, P2

#124 Add: updated http client for skynet
  skynet/skynet.go
Labels: bug, P1

#95 GitHub auth
  .github/workflows/golangci-lint.yml
  .github/workflows/oci-dist-spec-content-discovery.yml
  .github/workflows/oci-dist-spec-content-management.yml
  .github/workflows/oci-dist-spec-pull.yml
  .github/workflows/oci-dist-spec-push.yml
  Makefile
  auth/auth.go
  auth/basic_auth.go
  auth/github.go
  auth/jwt.go
  auth/signin.go
  auth/signup.go
  auth/token.go
  auth/validate_user.go
  config.yaml.example
  config/config.go
  db/migrations/000001_create_users_table.up.sql
  db/migrations/000006_create_sessions_table.down.sql
  db/migrations/000006_create_sessions_table.up.sql
  go.mod
  go.sum
  main.go
  router/helpers.go
  router/router.go
  store/postgres/auth.go
  store/postgres/postgres.go
  store/postgres/queries/auth.go
  store/postgres/queries/users.go
  store/postgres/users.go
  telemetry/fluent-bit/fluent_bit.go
  telemetry/log.go
  types/auth.go
  types/users.go
Labels: enhancement, P1

#126 Renew access token
  Makefile
  auth/auth.go
  auth/basic_auth.go
  auth/github.go
  auth/jwt.go
  auth/jwt_middleware.go
  auth/renew.go
  auth/sessions.go
  auth/signin.go
  auth/signout.go
  auth/signup.go
  auth/token.go
  auth/user.go
  auth/validate_user.go
  db/migrations/000002_create_blob_table.up.sql
  db/migrations/000003_create_layer_table.up.sql
  db/migrations/000004_create_config_table.up.sql
  db/migrations/000005_create_image_manifest_table.up.sql
  db/migrations/000006_create_session_table.down.sql
  db/migrations/000006_create_session_table.up.sql
  db/migrations/000006_create_sessions_table.down.sql
  db/migrations/000006_create_sessions_table.up.sql
  main.go
  registry/v2/extensions/catalog_detail.go
  registry/v2/registry.go
  registry/v2/types.go
  router/helpers.go
  router/route_names.go
  router/router.go
  skynet/skynet.go
  store/postgres/container_image.go
  store/postgres/postgres.go
  store/postgres/queries/auth.go
  store/postgres/queries/registry.go
  store/postgres/queries/users.go
  store/postgres/sessions.go
  store/postgres/users.go
  types/auth.go
  types/types.go
  types/users.go
Labels: enhancement, P1

#127 Add: logging for newly merged code
  auth/github.go
  auth/jwt_middleware.go
  auth/renew.go
  auth/sessions.go
  auth/signin.go
  auth/signout.go
  auth/signup.go
  auth/user.go
  go.mod
  registry/v2/blobs.go
  registry/v2/registry.go
Labels: enhancement

#128 Refactor: removed all occurrences of KV/Badger store
  auth/auth.go
  cache/register_for_beta.go
  cache/store.go
  main.go
  registry/v2/registry.go
  registry/v2/types.go
  router/helpers.go
  router/router.go
  store/postgres/container_image.go
  store/postgres/postgres.go
  store/postgres/queries/registry.go
Labels: enhancement

#129 Refactor: removed session struct and auth from types.go
  types/auth.go
Labels: Chore

#130 Add: sort images with namespace and last_updated
  registry/v2/extensions/catalog_detail.go
  store/postgres/container_image.go
  store/postgres/postgres.go
  store/postgres/queries/registry.go
Labels: enhancement

#131 Feat: email verification
  auth/auth.go
  auth/basic_auth.go
  auth/github.go
  auth/jwt.go
  auth/signin.go
  auth/signup.go
  auth/verify_email.go
  config.yaml.example
  config/config.go
  db/migrations/000007_create_verify_emails_table.down.sql
  db/migrations/000007_create_verify_emails_table.up.sql
  go.mod
  go.sum
  main.go
  registry/v2/registry.go
  registry/v2/types.go
  router/helpers.go
  router/route_names.go
  router/router.go
  services/email/createEmail.go
  services/email/email.go
  services/email/sendEmail.go
  store/postgres/postgres.go
  store/postgres/queries/verify_email.go
  store/postgres/users.go
  types/types.go
  types/users.go
Labels: enhancement, P1

#132 Password management apis
  auth/auth.go
  auth/bcrypt.go
  auth/invites.go
  auth/jwt.go
  auth/jwt_middleware.go
  auth/renew.go
  auth/reset_password.go
  auth/signin.go
  auth/signup.go
  auth/verify_email.go
  config/config.go
  router/helpers.go
  services/email/createEmail.go
  services/email/email.go
  services/email/sendEmail.go
  services/email/welcome_email.go
  store/postgres/postgres.go
  store/postgres/queries/users.go
  store/postgres/queries/verify_email.go
  store/postgres/users.go
  types/types.go
Labels: enhancement, P2
