Repository containerish/OpenRegistry, pull requests merged in 2022-04, with the labels that each got.

#134 Enhanced Logging
  auth/auth.go
  auth/github.go
  auth/invites.go
  auth/jwt.go
  auth/jwt_middleware.go
  auth/renew.go
  auth/reset_password.go
  auth/sessions.go
  auth/signin.go
  auth/signout.go
  auth/signup.go
  auth/token.go
  auth/user.go
  auth/verify_email.go
  config/config.go
  registry/v2/blobs.go
  registry/v2/extensions/catalog_detail.go
  registry/v2/registry.go
  router/helpers.go
  router/router.go
  scripts/mock-images.sh
  services/email/createEmail.go
  services/email/email.go
  services/email/welcome_email.go
  skynet/skynet.go
  store/postgres/container_image.go
  store/postgres/postgres.go
  store/postgres/queries/registry.go
  store/postgres/queries/users.go
  store/postgres/users.go
  telemetry/consoleWriter.go
Labels: enhancement

#138 Hotfix
  auth/github.go
  auth/jwt.go
  auth/user.go
  config.yaml.example
  go.mod
  go.sum
  main.go
  router/router.go
  skynet/skynet.go
  skynet/types.go
Labels: bug, enhancement, P3

#139 Add: read configuration from environment variable
  config/config.go
  config/yaml.go
  go.mod
Labels: enhancement, P3
