Repository containerish/OpenRegistry, pull requests merged in 2022-05, with the labels that each got.

#141 Fix: config validation before starting the service avoids panic
  config.yaml.example
  config/config.go
  config/yaml.go
  go.mod
  go.sum
Labels: bug, enhancement

#142 Fix: github redirect
  auth/github.go
Labels: bug

#143 Fix: safe alternative to uuid.New() and uuid.NewString() functions
  auth/github.go
  auth/signin.go
  auth/signup.go
  auth/verify_email.go
  registry/v2/registry.go
  router/router.go
  store/postgres/users.go
  telemetry/fluent-bit/fluent_bit.go
Labels: enhancement

#144 Fix: yaml version from 2.4.0 to 3.0.0
  go.mod
  go.sum
Labels: bug

#145 Upgrade CodeQL Github Action
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
Labels: Chore
