Repository containerish/OpenRegistry, pull requests merged in 2023-03, with the labels that each got.

#296 fix(ci): Use unique names for OCI report output files
  .github/workflows/oci-dist-spec-content-discovery.yml
  .github/workflows/oci-dist-spec-content-management.yml
  .github/workflows/oci-dist-spec-pull.yml
  .github/workflows/oci-dist-spec-push.yml
Labels: bug

#297 add(ci): GitHub Actions debugging
  .github/workflows/oci-dist-spec-content-discovery.yml
  .github/workflows/oci-dist-spec-content-management.yml
  .github/workflows/oci-dist-spec-pull.yml
  .github/workflows/oci-dist-spec-push.yml
Labels: Chore, CI, github_actions

#303 fix: Upload progress byte size
  registry/v2/registry.go
Labels: bug

#304 fix: JWT parsing in middlewares
  auth/jwt_middleware.go
Labels: bug

#195 feat: Password-less login with WebAuthn
  .github/workflows/oci-dist-spec-content-discovery.yml
  .github/workflows/oci-dist-spec-content-management.yml
  .github/workflows/oci-dist-spec-pull.yml
  .github/workflows/oci-dist-spec-push.yml
  .gitignore
  auth/auth.go
  auth/github.go
  auth/helpers.go
  auth/jwt.go
  auth/jwt_middleware.go
  auth/renew.go
  auth/reset_password.go
  auth/server/webauthn_server.go
  auth/signin.go
  auth/signout.go
  auth/signup.go
  auth/validate_user.go
  auth/verify_email.go
  auth/webauthn/types.go
  auth/webauthn/webauthn.go
  config.example.yaml
  config/config.go
  db/migrations/000001_create_users_table.up.sql
  db/migrations/000008_create_web_authn_creds_table.down.sql
  db/migrations/000008_create_web_authn_creds_table.up.sql
  db/migrations/000009_create_web_authn_session_table.down.sql
  db/migrations/000009_create_web_authn_session_table.up.sql
  go.mod
  go.sum
  main.go
  router/helpers.go
  router/route_names.go
  router/router.go
  router/webauthn_routes.go
  store/postgres/auth.go
  store/postgres/postgres.go
  store/postgres/queries/users.go
  store/postgres/queries/web_authn.go
  store/postgres/users.go
  store/postgres/web_authn.go
  types/users.go
Labels: enhancement, P1, Security

#193 GitHub app integration
  .github/workflows/dispatch.yml
  .github/workflows/oci-dist-spec-content-discovery.yml
  .github/workflows/oci-dist-spec-content-management.yml
  .github/workflows/oci-dist-spec-pull.yml
  .github/workflows/oci-dist-spec-push.yml
  .gitignore
  auth/auth.go
  auth/basic_auth.go
  auth/github.go
  auth/invites.go
  auth/jwt_middleware.go
  auth/renew.go
  auth/reset_password.go
  auth/server/webauthn_server.go
  auth/sessions.go
  auth/signin.go
  auth/signout.go
  auth/signup.go
  auth/token.go
  auth/user.go
  auth/validate_user.go
  auth/verify_email.go
  config/config.go
  db/migrations/000008_create_users_table.down.sql
  db/migrations/000008_create_users_table.up.sql
  db/migrations/000009_create_web_authn_creds_table.down.sql
  db/migrations/000009_create_web_authn_creds_table.up.sql
  db/migrations/000010_create_web_authn_session_table.down.sql
  db/migrations/000010_create_web_authn_session_table.up.sql
  go.mod
  go.sum
  main.go
  registry/v2/blobs.go
  registry/v2/extensions/catalog_detail.go
  registry/v2/registry.go
  router/router.go
  store/postgres/postgres.go
  store/postgres/queries/users.go
  store/postgres/users.go
  telemetry/consoleWriter.go
  telemetry/log.go
  types/users.go
  vcs/github/actions.go
  vcs/github/github.go
  vcs/github/handlers.go
  vcs/github/workflow.go
  vcs/vcs.go
Labels: enhancement, P1, CI, github_actions

#305 feat: Storj integration with Uplink
  .github/workflows/oci-dist-spec-content-discovery.yml
  .github/workflows/oci-dist-spec-content-management.yml
  .github/workflows/oci-dist-spec-pull.yml
  .github/workflows/oci-dist-spec-push.yml
  config.example.yaml
  config/config.go
  dfs/client/client.go
  dfs/storj/uplink/client.go
  dfs/storj/uplink/options.go
  dfs/storj/uplink/uplink.go
  go.mod
  go.sum
  main.go
Labels: enhancement, P1
